---
- name: Install Docker on Ubuntu, deploy project, and run docker compose
  hosts: all
  become: yes

  vars:
    project_remote_dir: /home/wrqs/web

    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  tasks:
    - name: Cleanup conflicting Docker apt sources and keyrings (no apt update yet)
      block:
        - name: Remove any docker/download apt source list files
          shell: "rm -f /etc/apt/sources.list.d/*docker*.list /etc/apt/sources.list.d/*download*.list"
          changed_when: false

        - name: Remove conflicting docker keyrings (asc/gpg)
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - /etc/apt/keyrings/docker.asc
            - /etc/apt/keyrings/docker.gpg

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Ensure /etc/apt/keyrings exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker GPG key (dearmor)
      shell: |
        set -e
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod 0644 /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Get dpkg architecture
      command: dpkg --print-architecture
      register: dpkg_arch
      changed_when: false

    - name: Add Docker repository (write /etc/apt/sources.list.d/docker.list)
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        mode: "0644"
        content: |
          deb [arch={{ dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    - name: apt update (with docker key present)
      apt:
        update_cache: yes

    - name: Remove old Docker packages
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
        purge: yes
      ignore_errors: yes

    - name: Install Docker packages
      apt:
        name: "{{ docker_packages }}"
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Create remote project dir
      file:
        path: "{{ project_remote_dir }}"
        state: directory
        mode: "0755"

    - name: Copy project directory to remote host
      copy:
        src: "{{ playbook_dir }}/"
        dest: "{{ project_remote_dir }}/"
        mode: preserve

    - name: Run docker compose up -d (as root)
      command: docker compose up -d
      args:
        chdir: "{{ project_remote_dir }}"
      register: compose_up
      changed_when: >
        ('Started' in compose_up.stdout) or
        ('Recreated' in compose_up.stdout) or
        ('Created' in compose_up.stdout) or
        ('Pulling' in compose_up.stdout)

    - name: Show docker compose output
      debug:
        var: compose_up.stdout

    - name: Show docker compose ps
      command: docker compose ps
      args:
        chdir: "{{ project_remote_dir }}"
      register: compose_ps
      changed_when: false

    - name: Compose status
      debug:
        var: compose_ps.stdout
